### ISSUE TITLE
Avoiding duplicate test naming?

### ISSUE THREAD

**Issue by rwjblue** [mike-north/ember-qunit-decorators#2]
Naming is hard. The existing APIs documented in the README is **doubly hard** because it requires developers to come up with _two_ names for each test.  I believe this can be avoided...

Current:

```ts
@suite("Integration | Helper | capitalize")
export class CapitalizeHelperTest extends EmberRenderingTest {

  @test("it renders")
  async itWorks(assert: Assert) {
    this.set("inputValue", "hello");

    await render(hbs`{{capitalize inputValue}}`);

    assert.equal(('' + this.element.textContent).trim(), "Hello");
  }
}
```

Proposal:

```ts
@suite("Integration | Helper | capitalize")
export class CapitalizeHelperTest extends EmberRenderingTest {

  @test async 'it renders'(assert: Assert) {
    this.set("inputValue", "hello");

    await render(hbs`{{capitalize inputValue}}`);

    assert.equal(('' + this.element.textContent).trim(), "Hello");
  }
}
```

See, its twice as easy! 😉 

This syntax works both in TS ([playground example](https://www.typescriptlang.org/play/index.html#src=%40suite(%22Integration%20%7C%20Helper%20%7C%20capitalize%22)%0D%0Aexport%20class%20CapitalizeHelperTest%20extends%20EmberRenderingTest%20%7B%0D%0A%0D%0A%20%20%40test%20async%20'it%20renders'(assert%3A%20Assert)%20%7B%0D%0A%20%20%20%20this.set(%22inputValue%22%2C%20%22hello%22)%3B%0D%0A%0D%0A%20%20%20%20await%20render(hbs%60%7B%7Bcapitalize%20inputValue%7D%7D%60)%3B%0D%0A%0D%0A%20%20%20%20assert.equal((''%20%2B%20this.element.textContent).trim()%2C%20%22Hello%22)%3B%0D%0A%20%20%7D%0D%0A%7D)) and JS ([babel repl example](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=AIZwrglgLgpgFAIgJIDtYHMBOBDKED2KABAD5EASMANgA4yalEDG2N02VEAXjAgJQAoGAA8a-TFGZVsIEEQDCrdpx6Va9ACowQkkbBQATOQFEAtgCN6AJRiH6EFOi06iAbwECiRYLBcyAnihMRADk0ESYtgb0ICFwMiD0UABcRACCskl8bp5eRFAAFhAgAHSJUIgONGBQAGocYLwANEQIBdRU-PwA3B55RNgA7tjhkXaYcAXmIAAGrq4sbFAc3DBEVTX1VI0AvjszfL25XglJJTAAjmAccHAhIUQA1PlFpdQwprZQJbDCUPKEfRQPg_TAQUxwPgtBBqTo9XI7AQ7IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)).

**Comment by rwjblue** [comment]
Dangit, sorry, I think I should have reported this against qunit-decorators itself.

**Comment by mike-north** [comment]
If this is legal decorator syntax, I’m happy to add it as an overload

**Comment by rwjblue** [comment]
Hmm, I don't think it has to do with the decorator at all. Its just valid method definition syntax.

Try this out in Chrome console:

```js
(() => {
  'use strict';

  class Foo {
    'lololol'() { console.log('lol'); }
  }
  let f = new Foo();
  f.lololol()
})();
```

**Comment by mike-north** [comment]
`'haha lol'` indeed. I didn't know this was possible. This issue will get closed once I update the readme appropriately
